uploads = []
generated = []

[[outputs]]
id = "Uj3aFe9h6PqEONHqcTuPO"
uri = "file://attached_assets/FexDXVK-NonAdreno.winlator"
type = "unspecified"
title = "FexDXVK-NonAdreno.winlator — updated 23 MB package"
