kind = "web"
previewPath = "/"
title = "FexDXVK Configurator"
version = "1.0.0"
id = "artifacts/fexdxvk-configurator"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22687

[services.development]
run = "pnpm --filter @workspace/fexdxvk-configurator run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/fexdxvk-configurator", "run", "build" ]
serve = "static"
publicDir = "artifacts/fexdxvk-configurator/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22687"
BASE_PATH = "/"
